version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: minha-api:latest
    container_name: backend_spring
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
