name: Deploy Infra + App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deploy
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Setup Python & Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCLOUD_SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine
      
      - name: Run Ansible Playbook (Database)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i ansible-database/inventory.ini ansible-database/playbook.yml

      - name: Run Ansible Playbook (Backend)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
