name: Deploy Infra + Backend + DB

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Ansible e Terraform no runner (se necessário)
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y terraform ansible


      - name: Provisionar infraestrutura com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Rodar Ansible - Configurar backend
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
