name: Deploy Infra + App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deploy
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve

      - name: Setup Python & Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Debug secret length
        run: |
          echo "Key size: $(echo "${{ secrets.GCLOUD_SSH_PRIVATE_KEY }}" | wc -c)"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/google_compute_engine
          ${{ secrets.GCLOUD_SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/google_compute_engine
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/google_compute_engine



      - name: Run Ansible Playbook
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
