name: Deploy Infra + Backend + DB

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Ansible e Terraform no runner
        run: |
          sudo apt update
          sudo apt install -y ansible terraform

      - name: Provisionar infraestrutura com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Rodar Ansible - Configurar backend
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
